### ISSUE TITLE
侧边栏工具插件能否自定义图标？

### ISSUE THREAD

**Issue by gdqsfuture** [zuoez02/siyuan-plugin-toolbar-plus#12]
大佬您好，侧边栏工具对快捷访问某个块非常方便，现在就是固定在侧边栏后，图标都是一个笑脸，当块的数目多了后，不好区分，能否在设置里面自定义块的emoji图标么？谢谢

**Comment by zuoez02** [comment]
后续版本支持
________________________________
发件人: guogdq ***@***.***>
发送时间: 2024年1月16日 17:20
收件人: zuoez02/siyuan-plugin-toolbar-plus ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zuoez02/siyuan-plugin-toolbar-plus] 侧边栏工具插件能否自定义图标？ (Issue #12)


大佬您好，侧边栏工具对快捷访问某个块非常方便，现在就是固定在侧边栏后，图标都是一个笑脸，当块的数目多了后，不好区分，能否在设置里面自定义块的emoji图标么？谢谢

―

**Comment by zuoez02** [comment]
参见v0.3.0

**Comment by gdqsfuture** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好，效率真高！已经更新，有两个问题1、不知道哪里可以找到图标的id2、config.json文件里面，docks和ids后面代码都是一样的图标id，是需要一起修改么。还要请您抽空指点一下，谢谢哈
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                guogdq
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Luto ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年01月16日 23:42
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [zuoez02/siyuan-plugin-toolbar-plus] 侧边栏工具插件能否自定义图标？ (Issue #12)
        
      
    
  
  
参见v0.3.0

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
