### ISSUE TITLE
工具栏遮挡住了“退出聚焦按钮”

### ISSUE THREAD

**Issue by edward-kyle** [zuoez02/siyuan-plugin-toolbar-plus#2]
![60dfe77011a179eb0764016b88fbfa58](https://github.com/zuoez02/siyuan-plugin-toolbar-plus/assets/78415230/0785c25b-5a2d-4d32-9df9-ec736bda5eef)
如图，进入大纲聚焦模式，右上角的退出聚焦恰好被挡住了。
希望可以解决这个问题。

思源版本：2.10.5
主题：savor、pinkroom都有出现

**Comment by OpaqueGlass** [comment]
hi，我是文档面包屑插件的作者，您似乎启用了文档面包屑插件？在面包屑插件设置里启用“与块面包屑在同一行显示”，应该可以解决这个问题。

**Comment by edward-kyle** [comment]
在工具栏plsu插件v1.1.0版本、siyuan v2.10.6-dev2解决了。
