### ISSUE TITLE
不能显示按钮名称

### ISSUE THREAD

**Issue by 782669218** [zuoez02/siyuan-plugin-toolbar-plus#7]
你好，我发现这个插件不能显示按钮名称，更新最新版siyuan和插件后依然不可以，同时测试是否取消钉住也是不显示。关闭插件后显示正常。

![PixPin_2023-12-07_16-28-09](https://github.com/zuoez02/siyuan-plugin-toolbar-plus/assets/40153758/a0724c64-8829-4763-99bc-8abb42d1bea9)
![PixPin_2023-12-07_16-27-33](https://github.com/zuoez02/siyuan-plugin-toolbar-plus/assets/40153758/4f1145eb-b935-4115-9fc3-e0f4bd903656)

**Comment by zuoez02** [comment]
看下主题，我这用默认主题正常的

**Comment by 782669218** [comment]
我刚刚测试了下默认主题确实可以！感谢！那应该是主题的适配问题了。
